#!/bin/bash
###
#
###
KEYSTONERC="/home/admin-openrc"
ports=$(netstat -nltp | egrep -w '5000|35357')
apache_flag=$(systemctl status apache2 | grep -w 'active (running)')

if [ -z "$ports" ] && [ -z "$apache_flag" ]
then
        echo "apache2 or KEYSTONE is/are not running."
        exit 2
else
        source $KEYSTONERC > /dev/null 2>&1
        openstack token issue > /tmp/err_keystone.h2 2>&1
        token=$(cat /tmp/err_keystone.h2 | egrep -w "Missing value|HTTP 401")
        rm -rf /tmp/err_keystone.h2
        if [ -n "$token" ]
        then
                echo -e "Keystone is running. Can't get token!!! Check your \"$KEYSTONERC\" files."

                exit 1
        else
                echo "KEYSTONE is running."
                exit 0
        fi
fi
